id: P008031
initial_creation_type: ocr
source_metadata:
  id: bdr:W25114
  title: འཐུས་སྒོ་ཚང་བའི་བསམ་བློ།
  author: ''
  volumes:
    85c893775bfb4aac909c0ba154ca0348:
      image_group_id: I1KG12344
      title: ''
      volume_number: 1
      total_pages: 434
ebook_metadata:
  title: འཐུས་སྒོ་ཚང་བའི་བསམ་བློ།
  author: ''
  sku: P008031
  cover: cover.jpg
  layers:
  - pagination
