id: P008031
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:56:41.880469
source_metadata:
  id: bdr:W25114
  title: འཐུས་སྒོ་ཚང་བའི་བསམ་བློ།
  author: ''
  volumes:
    d579d00af82b4482b96c53bc8296b84e:
      image_group_id: I1KG12344
      title: Volume 1 of 'thus sgo tshang ba'i bsam blo/
      volume_number: 1
      total_pages: 434
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
