id: IFBDB96B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T01:39:54+00:00'
last_modified: '2022-06-08T17:56:31.710270+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25114
  title: འཐུས་སྒོ་ཚང་བའི་བསམ་བློ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '6047':
      image_group_id: I1KG12344
      title: Volume 1 of 'thus sgo tshang ba'i bsam blo/
      total_pages: 434
      order: 1
      base_file: 6047.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
